import {
  MidDataType, BottomDataType, RunningCaseDataType,
} from './data.d';


const ActForecastMidData ={
  periodFrom: '202007',
  periodTo: '202009',
  averageOrSame: false,
  amount1: '',
  effort1: '',
  amount2: '',
  effort2: '',
  amount3: '',
  effort3: '',
  amount4: '',
  effort4: '',
  amount5: '',
  effort5: '',
  amount6: '',
  effort6: '',
  amount7: '',
  effort7: '',
  amount8: '',
  effort8: '',
  amount9: '',
  effort9: '',
  amount10: '',
  effort10: '',
  amount11: '',
  effort11: '',
  amount12: '',
  effort12: '',
  totalAmount: '',
  totalEffort: '',
}

const ActBottomData = [
  {
    key:'1',
    No: '1',
    customer:'NRI',
    industry:'securities',
    case:'case A',
    caseNumber:'N001',
    probability:'A',
    amount:'12135409',
    currency:'JPY',
    effort:'32',
    effortUnit:'MM',
    accounting:'Ritatsu Soft',
    department:'department 1',
    endUser:'NRI',
    remarks:'Jenuary',
    editable:false,
  },
  {
    key:'2',
    No: '2',
    customer:'NRI',
    industry:'securities',
    case:'case A',
    caseNumber:'N001',
    probability:'A',
    amount:'12135409',
    currency:'JPY',
    effort:'32',
    effortUnit:'MM',
    accounting:'Ritatsu Soft',
    department:'department 1',
    endUser:'NRI',
    remarks:'Jenuary',
    editable:false,
  },
  {
    key:'3',
    No: '3',
    customer:'NRI',
    industry:'securities',
    case:'case A',
    caseNumber:'N001',
    probability:'A',
    amount:'12135409',
    currency:'JPY',
    effort:'32',
    effortUnit:'MM',
    accounting:'Ritatsu Soft',
    department:'department 1',
    endUser:'NRI',
    remarks:'Jenuary',
    editable:false,
  },
]

const RunningCaseData = [
  {
    key:'1',
    No: '1',
    division:'new',
    startDate:'2020.01',
    customer:'NRI',
    industry:'securities',
    case:'case A',
    estimatedAmount:'12135409',
    contractCurrency:'JPY',
    estimatedEffort:'32',
    effortUnit:'MM',
    orderDate:'2020.06',
    probability:'A',
    remarks:'Jenuary',
    editable:false,
  },
  {
    key:'2',
    No: '2',
    division:'new',
    startDate:'2020.01',
    customer:'NRI',
    industry:'securities',
    case:'case A',
    estimatedAmount:'12135409',
    contractCurrency:'JPY',
    estimatedEffort:'32',
    effortUnit:'MM',
    orderDate:'2020.06',
    probability:'A',
    remarks:'Jenuary',
    editable:false,
  },
  {
    key:'3',
    No: '3',
    division:'new',
    startDate:'2020.01',
    customer:'NRI',
    industry:'securities',
    case:'case A',
    estimatedAmount:'12135409',
    contractCurrency:'JPY',
    estimatedEffort:'32',
    effortUnit:'MM',
    orderDate:'2020.06',
    probability:'A',
    remarks:'Jenuary',
    editable:false,
  },
]

const ActMidDataType :MidDataType = {
  ActForecastMidData,
}

const ActBottomDataType :BottomDataType = {
  ActBottomData,
}

const RunCaseDataType :RunningCaseDataType = {
  RunningCaseData,
}


export default {
  'GET  /api/getActForecastMidData': ActMidDataType,
  'GET  /api/getActForecastBottomData': ActBottomDataType,
  'GET  /api/getRunningCaseData': RunCaseDataType,
};
