version: '3.5'

networks:
  &network server:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: 172.26.30.0/16
services:
  ant-design-pro-build:
    build: ../
    ports:
      - 8078:8000    
    tty: true
    container_name: 'ant-design-pro-build'
    restart: unless-stopped    
    volumes:
      - ../:/usr/src/app/:rw

    networks:
      *network :
        ipv4_address: 172.26.30.1    

  ant-design-pro_web:
    image: nginx
    ports:
      - 8086:80
    container_name: 'ant-design-pro_web'
    restart: unless-stopped
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf    
    networks:
      *network :
        ipv4_address: 172.26.30.2   

  ant-design-pro-openweb:
    build:
      context: ../
      dockerfile: Dockerfile.openresty    
    ports:
      - 8079:80
    container_name: 'ant-design-pro-openweb'
    restart: unless-stopped
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./prod.conf:/etc/nginx/conf.d/default.conf
      - ./opennginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./lua:/usr/local/openresty/nginx/lua
      - ./lua/http_headers.lua:/usr/local/openresty/lualib/resty/http_headers.lua      
    networks:
      *network :
        ipv4_address: 172.26.30.3                      
volumes:
  dist:
